//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teman_ApotikProj.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Obat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Obat()
        {
            this.Harga = new HashSet<Harga>();
            this.ObatKeluar = new HashSet<ObatKeluar>();
            this.ObatMasuk = new HashSet<ObatMasuk>();
            this.StokObat = new HashSet<StokObat>();
        }

        
        public int Id_Obat { get; set; }
        [StringLength(20, ErrorMessage = "Minimal {0} karakter dan minimal {2} panjang karakter", MinimumLength = 4)]
        [Required(ErrorMessage = "Kode Obat wajib ditulis")]
        [RegularExpression("^[[a-zA-Z0-9]]*$", ErrorMessage = "Masukan terdiri dari angka dan huruf !")]
        public string Kode_Obat { get; set; }

        [StringLength(20, ErrorMessage = "Minimal {0} karakter dan harus {2} panjang karakter", MinimumLength = 4)]
        [Required(ErrorMessage = "Nama Obat wajib ditulis")]
        [RegularExpression("^[a-zA-Z]*$", ErrorMessage = "Masukan hanya huruf !")]
        public string Nama_Obat { get; set; }

        public Nullable<int> Id_Jenis_Obat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Harga> Harga { get; set; }
        public virtual JenisObat JenisObat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObatKeluar> ObatKeluar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObatMasuk> ObatMasuk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StokObat> StokObat { get; set; }
    }
}
