//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teman_ApotikProj.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ObatMasuk
    {
        public int Id_Transaksi_Masuk { get; set; }
        public Nullable<int> Id_Obat { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Tgl_Masuk { get; set; }

        public Nullable<int> Id_Supplier { get; set; }
        public Nullable<int> Id_Jenis_Obat { get; set; }
        public Nullable<int> Jumlah_Masuk { get; set; }
        public Nullable<int> Harga_Beli { get; set; }
    
        public virtual Obat Obat { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
