//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teman_ApotikProj.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pasien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pasien()
        {
            this.ObatKeluar = new HashSet<ObatKeluar>();
        }
    
        public int Id_Pasien { get; set; }
        [StringLength(20, MinimumLength = 3)]
        [Required(ErrorMessage = "Nama wajib tulis!")]
        [RegularExpression("^[a-zA-Z]*$", ErrorMessage = "Masukan hanya huruf!")]
        public string Nama_Pasien { get; set; }
        [Required(ErrorMessage = "Nama wajib tulis!")]
        [RegularExpression("^[a-zA-Z]*$", ErrorMessage = "Masukan hanya huruf!")]
        public string Alamat_Pasien { get; set; }
        [Required(ErrorMessage = "Nama wajib tulis!")]
        [RegularExpression("^[a-zA-Z]*$", ErrorMessage = "Masukan hanya huruf!")]
        public string Diagnosa_Penyakit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObatKeluar> ObatKeluar { get; set; }
    }
}
