//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teman_ApotikProj.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.ObatMasuk = new HashSet<ObatMasuk>();
        }
    
        public int Id_Supplier { get; set; }
        [StringLength(20, ErrorMessage = "Panjang maksimal {0} Karakter dan minimal {1} karakter", MinimumLength = 10)]
        [Required(ErrorMessage = "Nama wajib tulis!")]
        [RegularExpression("^[a-zA-Z]*$", ErrorMessage = "Masukan hanya huruf!")]
        public string Nama_Suplier { get; set; }
        public Nullable<int> Id_Jenis_Obat { get; set; }
        public string Alamat_Supplier { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObatMasuk> ObatMasuk { get; set; }
    }
}
