//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teman_ApotikProj.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TemanApotikkEntities : DbContext
    {
        public TemanApotikkEntities()
            : base("name=TemanApotikkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Harga> Harga { get; set; }
        public virtual DbSet<JenisObat> JenisObat { get; set; }
        public virtual DbSet<Obat> Obat { get; set; }
        public virtual DbSet<ObatKeluar> ObatKeluar { get; set; }
        public virtual DbSet<ObatMasuk> ObatMasuk { get; set; }
        public virtual DbSet<Pasien> Pasien { get; set; }
        public virtual DbSet<StokObat> StokObat { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
    }
}
